sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean package -U
  - docker build -t cleptes/album ./album
  - docker build -t cleptes/artist ./artist

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push cleptes/album
  - docker push cleptes/artist